# app/config/routing.yml

innovare_user:
    resource: "@InnovareUserBundle/Resources/config/routing.yml"
    prefix:   /

innovare_main:
    resource: "@InnovareMainBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /
