innovare_main_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: InnovareMainBundle:Default:index }

innovare_main_addLaboratorio:
    pattern:  /addLaboratorio
    defaults: { _controller: InnovareMainBundle:Default:addLaboratorio }
