parameters:
#    innovare_main.example.class: Innovare\MainBundle\Example

services:
#    innovare_main.example:
#        class: %innovare_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
