parameters:
#    innovare_user.example.class: Innovare\UserBundle\Example

services:
#    innovare_user.example:
#        class: %innovare_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
