Innovare\MainBundle\Entity\Area:
    type: entity
    table: area
    id:
        idArea:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_area
            generator:
                strategy: IDENTITY
    fields:
        area:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
        areaTresto:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: area_tresto
    lifecycleCallbacks: {  }
