Innovare\MainBundle\Entity\LaboratorioFoto:
    type: entity
    table: laboratorio_foto
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idLaboratorio:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: id_laboratorio
        nomefile:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
