Innovare\MainBundle\Entity\MiurSsd:
    type: entity
    table: miur_ssd
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ssd:
            type: string
            nullable: false
            length: 15
            fixed: false
            comment: ''
        ssdDesc:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            column: ssd_desc
    lifecycleCallbacks: {  }
