Innovare\MainBundle\Entity\MiurArea:
    type: entity
    table: miur_area
    id:
        miurArea:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: miur_area
            generator:
                strategy: IDENTITY
    fields:
        miurAreaDesc:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            column: miur_area_desc
    lifecycleCallbacks: {  }
