Innovare\MainBundle\Entity\Servizi:
    type: entity
    table: servizi
    id:
        idServizi:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_servizi
            generator:
                strategy: IDENTITY
    fields:
        descrizione:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
