Innovare\MainBundle\Entity\Settore:
    type: entity
    table: settore
    id:
        idSettore:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_settore
            generator:
                strategy: IDENTITY
    fields:
        settore:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
        settoreTresto:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: settore_tresto
    lifecycleCallbacks: {  }
