Innovare\MainBundle\Entity\XAreaSettore:
    type: entity
    table: x_area_settore
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idArea:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_area
        idSettore:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_settore
    lifecycleCallbacks: {  }
