Innovare\MainBundle\Entity\XLabAnag:
    type: entity
    table: x_lab_anag
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idLaboratorio:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_laboratorio
        idAnagrafica:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_anagrafica
        tempo:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Percentuale di tempo '
    lifecycleCallbacks: {  }
