Innovare\MainBundle\Entity\XLabServStrum:
    type: entity
    table: x_lab_serv_strum
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idLaboratorio:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_laboratorio
        idStrumento:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_strumento
        idServizio:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_servizio
        tipologia:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: 'effetrtuato - effettuabile'
            default: effettuato
        motivazione:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: 'motivare perchè il servizio non è attualmente erogato'
    lifecycleCallbacks: {  }
