Innovare\MainBundle\Entity\XLabSupp:
    type: entity
    table: x_lab_supp
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idLaboratorio:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_laboratorio
        idServiziSupporto:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_servizi_supporto
        descrizione:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
