Innovare\MainBundle\Entity\XLabStrum:
    type: entity
    table: x_lab_strum
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idLaboratorio:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_laboratorio
        idStrumento:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_strumento
        quantita:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
